# install       pip3 install prek
# run           prek run -a  # or --all-files
# update deps   prek autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: forbid-new-submodules
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer

  - repo: builtin # preks faster versions
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-json
      - id: check-json5
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: mixed-line-ending
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      # - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.15.12'
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: ["--fix", "--exit-non-zero-on-fix"]

#  - repo: https://github.com/ansible-community/ansible-lint.git
#    rev: v6.22.1
#    hooks:
#      - id: ansible-lint
#        files: \.(yaml|yml)$

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.24.1
    hooks:
      - id: zizmor
        args: ["--min-severity", "high", "--no-progress", "--fix", "."]

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.2"
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]  # for py<3.11
