# Generated by Django 4.1 on 2022-08-18 23:21

from django.db import migrations, models
import django.db.models.deletion
import testbed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gpio",
            fields=[
                (
                    "name",
                    models.SlugField(max_length=30, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(max_length=1000)),
                ("comment", models.TextField(max_length=200)),
                ("direction", models.SlugField(max_length=2)),
                ("dir_switch", models.SlugField(max_length=10)),
                ("pin_pru", models.SlugField(max_length=10)),
                ("pin_bbp", models.SlugField(max_length=10)),
                ("pin_sys", models.SlugField(max_length=10)),
                ("pin_bbs", models.SlugField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "name",
                    models.SlugField(max_length=30, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(max_length=1000)),
                ("comment", models.TextField(max_length=200)),
                ("platform1", models.SlugField(max_length=10)),
                ("core1", models.SlugField(max_length=10)),
                ("programmer1", models.SlugField(max_length=10)),
                ("platform2", models.SlugField(max_length=10)),
                ("core2", models.SlugField(max_length=10)),
                ("programmer2", models.SlugField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Observer",
            fields=[
                (
                    "name",
                    models.SlugField(
                        help_text="String (up to %(max_length)s), only letters, numbers, underscores & hyphens",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="String (up to %(max_length)s)",
                        max_length=1000,
                        verbose_name="Description (verbose)",
                    ),
                ),
                ("comment", models.TextField(blank=True, default="", max_length=200)),
                ("ip", models.GenericIPAddressField(unique=True)),
                (
                    "mac",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        unique=True,
                        validators=[testbed.models.validate_mac],
                    ),
                ),
                ("room", models.SlugField(max_length=10)),
                ("eth_port", models.SlugField(max_length=20, unique=True)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "target_a",
                    models.OneToOneField(
                        blank=True,
                        help_text="Target board for Port A on Shepherd Cape",
                        on_delete=django.db.models.deletion.PROTECT,
                        parent_link=True,
                        related_name="connectedA",
                        to="testbed.target",
                        verbose_name="Target Port A",
                    ),
                ),
                (
                    "target_b",
                    models.OneToOneField(
                        blank=True,
                        help_text="Target board for Port B on Shepherd Cape",
                        on_delete=django.db.models.deletion.PROTECT,
                        parent_link=True,
                        related_name="connectedB",
                        to="testbed.target",
                        verbose_name="Target Port B",
                    ),
                ),
                (
                    "alive_last",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Timestamp of latest alive-message.",
                        verbose_name="Last seen",
                    ),
                ),
            ],
        ),

    ]
