# Generated by Django 4.1 on 2022-08-18 23:42

from django.db import migrations, models
import testbed.models


class Migration(migrations.Migration):

    dependencies = [
        ("testbed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpio",
            name="comment",
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="gpio",
            name="description",
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="gpio",
            name="dir_switch",
            field=models.SlugField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="observer",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="String (up to %(max_length)s)",
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="observer",
            name="ip",
            field=models.GenericIPAddressField(unique=True, verbose_name="IP-Address"),
        ),
        migrations.AlterField(
            model_name="observer",
            name="mac",
            field=models.CharField(
                blank=True,
                max_length=17,
                unique=True,
                validators=[testbed.models.validate_mac],
                verbose_name="MAC-Address",
            ),
        ),
        migrations.AlterField(
            model_name="observer",
            name="name",
            field=models.SlugField(
                help_text="String (up to %(max_length)s), only letters, numbers, underscores & hyphens",
                max_length=30,
                primary_key=True,
                serialize=False,
                verbose_name="Name of Observer",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="comment",
            field=models.TextField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="target",
            name="description",
            field=models.TextField(blank=True, default="", max_length=400),
        ),
    ]
