name: QA-Tests

on:
  push:
    branches: [ "main", "dev" ]
  workflow_call:
  workflow_dispatch:

jobs:
  static-analysis:
    uses: ./.github/workflows/static_analysis.yaml
  test-python:
    uses: ./.github/workflows/py_tests.yaml

  quality-assurance:
    runs-on: ubuntu-latest
    needs:
      - static-analysis
      - test-python
    steps:
      - name: Finished
        run: echo "finished"
