name: Release tagged Commit

on:
  workflow_call:
  push:
    tags:
      - 'v*.*.*'
    # branches: [ main ]  # handled as OR! (push to main OR tagged)

permissions:
  contents: write

jobs:
  run-quality-assurance:
    uses: ./.github/workflows/quality_assurance.yaml
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - run-quality-assurance
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Release 🏃
        uses: softprops/action-gh-release@v2
