name: Static analysis

on:
  workflow_call:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Run Pre-Commit Tests 🧪
        uses: j178/prek-action@v2
